package com.dagomusic.core.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val appName: String,
    val unknownArtist: String,
    val unknownAlbum: String,
    val unknownSong: String,
    val navHome: String,
    val navLibrary: String,
    val navSearch: String,
    val navPlaylists: String,
    val navSettings: String,

    // Library Tabs
    val tabSongs: String,
    val tabArtists: String,
    val tabAlbums: String,
    val tabFolders: String,
    val tabGenres: String,

    // Home Sections
    val homeRecentlyPlayed: String,
    val homeMostPlayed: String,
    val homeFavorites: String,
    val homeRecentAlbums: String,
    val homeRecentArtists: String,
    val homePlaylists: String,
    val homeNewlyAdded: String,
    val homeSuggestions: String,
    val homeForgotten: String,

    // Equalizer
    val eqTitle: String,
    val eqBassBoost: String,
    val eqVirtualizer: String,
    val eqLoudness: String,
    val eqSavePreset: String,
    val eqReset: String,

    // Settings
    val settingsTitle: String,
    val settingsAppearance: String,
    val settingsThemeMode: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsThemeSystem: String,
    val settingsMaterialYou: String,
    val settingsDynamicColorArtwork: String,
    val settingsAudio: String,
    val settingsCrossfade: String,
    val settingsGapless: String,
    val settingsFadeIn: String,
    val settingsFadeOut: String,
    val settingsLibraryScan: String,
    val settingsMinDuration: String,
    val settingsMinSize: String,
    val settingsPerformance: String,
    val settingsEnableBlur: String,
    val settingsBackup: String,
    val settingsBackupLocal: String,
    val settingsRestoreLocal: String,
    val settingsLanguage: String,
    val settingsAbout: String,
    val settingsVersion: String,

    // Actions
    val actionPlay: String,
    val actionPlayNext: String,
    val actionAddToQueue: String,
    val actionAddToPlaylist: String,
    val actionFavorite: String,
    val actionRemoveFavorite: String,
    val actionShare: String,
    val actionDelete: String,
    val actionRename: String,
    val actionProperties: String,
    val actionOpenFolder: String,
    val actionCancel: String,
    val actionSave: String,
    val actionOk: String,

    // Search
    val searchPlaceholder: String,
    val searchRecent: String,
    val searchNoResults: String,

    // Playback
    val playbackSpeed: String,
    val playbackPitch: String,
    val playbackBalance: String,
    val playbackLyrics: String,
    val playbackSleepTimer: String,
    val sleepTimerOff: String,
    val sleepTimerMinutes: String,
    val sleepTimerCustom: String,
    val sleepTimerSet: String,

    // Metadata
    val metaTitle: String,
    val metaArtist: String,
    val metaAlbum: String,
    val metaPath: String,
    val metaSize: String,
    val metaDuration: String,
    val metaBitrate: String,
    val metaSampleRate: String,
    val metaCodec: String,
    val metaComposer: String,
    val metaGenre: String,
    val metaYear: String,

    // Messages
    val msgScanning: String,
    val msgScanComplete: String,
    val msgBackupSuccess: String,
    val msgRestoreSuccess: String,
    val msgRestoreFailed: String,
    val msgDeleteConfirm: String,
    val msgUnsupportedFile: String
)

val EnglishStrings = AppStrings(
    appName = "Dago Music",
    unknownArtist = "Unknown Artist",
    unknownAlbum = "Unknown Album",
    unknownSong = "Unknown Song",
    navHome = "Home",
    navLibrary = "Library",
    navSearch = "Search",
    navPlaylists = "Playlists",
    navSettings = "Settings",
    tabSongs = "Songs",
    tabArtists = "Artists",
    tabAlbums = "Albums",
    tabFolders = "Folders",
    tabGenres = "Genres",
    homeRecentlyPlayed = "Recently Played",
    homeMostPlayed = "Most Played",
    homeFavorites = "Favorites",
    homeRecentAlbums = "Recent Albums",
    homeRecentArtists = "Top Artists",
    homePlaylists = "Your Playlists",
    homeNewlyAdded = "Newly Added",
    homeSuggestions = "Smart Suggestions",
    homeForgotten = "Forgotten Tracks",
    eqTitle = "Equalizer",
    eqBassBoost = "Bass Boost",
    eqVirtualizer = "3D Virtualizer",
    eqLoudness = "Loudness Enhancer",
    eqSavePreset = "Save Preset",
    eqReset = "Reset",
    settingsTitle = "Settings",
    settingsAppearance = "Appearance",
    settingsThemeMode = "Theme Mode",
    settingsThemeLight = "Light",
    settingsThemeDark = "Dark",
    settingsThemeSystem = "System Default",
    settingsMaterialYou = "Material You (Dynamic Colors)",
    settingsDynamicColorArtwork = "Extract color from artwork",
    settingsAudio = "Audio Controls",
    settingsCrossfade = "Crossfade (seconds)",
    settingsGapless = "Gapless Playback",
    settingsFadeIn = "Fade In on Play",
    settingsFadeOut = "Fade Out on Pause",
    settingsLibraryScan = "Scan Settings",
    settingsMinDuration = "Ignore tracks shorter than (seconds)",
    settingsMinSize = "Ignore files smaller than (KB)",
    settingsPerformance = "Performance",
    settingsEnableBlur = "Enable Blur and Glassmorphism",
    settingsBackup = "Backup & Restore",
    settingsBackupLocal = "Backup to Local File",
    settingsRestoreLocal = "Restore from Local File",
    settingsLanguage = "Language / اللغة",
    settingsAbout = "About Dago Music",
    settingsVersion = "Version 1.1.0",
    actionPlay = "Play",
    actionPlayNext = "Play Next",
    actionAddToQueue = "Add to Queue",
    actionAddToPlaylist = "Add to Playlist",
    actionFavorite = "Favorite",
    actionRemoveFavorite = "Remove Favorite",
    actionShare = "Share File",
    actionDelete = "Delete Permanently",
    actionRename = "Rename File",
    actionProperties = "Properties",
    actionOpenFolder = "Open Folder",
    actionCancel = "Cancel",
    actionSave = "Save",
    actionOk = "OK",
    searchPlaceholder = "Search songs, artists, albums, folders…",
    searchRecent = "Recent Searches",
    searchNoResults = "No results found",
    playbackSpeed = "Playback Speed",
    playbackPitch = "Pitch",
    playbackBalance = "Audio Balance",
    playbackLyrics = "Lyrics",
    playbackSleepTimer = "Sleep Timer",
    sleepTimerOff = "Sleep Timer Off",
    sleepTimerMinutes = "%1\$d Minutes",
    sleepTimerCustom = "Custom Time (mins)",
    sleepTimerSet = "Set Sleep Timer",
    metaTitle = "Title",
    metaArtist = "Artist",
    metaAlbum = "Album",
    metaPath = "Path",
    metaSize = "Size",
    metaDuration = "Duration",
    metaBitrate = "Bitrate",
    metaSampleRate = "Sample Rate",
    metaCodec = "Codec",
    metaComposer = "Composer",
    metaGenre = "Genre",
    metaYear = "Year",
    msgScanning = "Scanning library…",
    msgScanComplete = "Scan completed. %1\$d songs found.",
    msgBackupSuccess = "Backup saved successfully!",
    msgRestoreSuccess = "Library restored successfully!",
    msgRestoreFailed = "Restore failed: File invalid.",
    msgDeleteConfirm = "Are you sure you want to permanently delete this file from your device? This cannot be undone.",
    msgUnsupportedFile = "Unable to play file. Unsupported format."
)

val ArabicStrings = AppStrings(
    appName = "داجو ميوزك",
    unknownArtist = "فنان غير معروف",
    unknownAlbum = "ألبوم غير معروف",
    unknownSong = "أغنية غير معروفة",
    navHome = "الرئيسية",
    navLibrary = "المكتبة",
    navSearch = "البحث",
    navPlaylists = "قوائم التشغيل",
    navSettings = "الإعدادات",
    tabSongs = "الأغاني",
    tabArtists = "الفنانون",
    tabAlbums = "الألبومات",
    tabFolders = "المجلدات",
    tabGenres = "الأنواع",
    homeRecentlyPlayed = "آخر تشغيل",
    homeMostPlayed = "الأكثر استماعاً",
    homeFavorites = "المفضلة",
    homeRecentAlbums = "أحدث الألبومات",
    homeRecentArtists = "الفنانون الأكثر استماعاً",
    homePlaylists = "قوائم التشغيل الخاصة بك",
    homeNewlyAdded = "أضيفت مؤخراً",
    homeSuggestions = "اقتراحات ذكية",
    homeForgotten = "أغانٍ منسية",
    eqTitle = "معادل الصوت",
    eqBassBoost = "زيادة الباص",
    eqVirtualizer = "تأثير مجسم",
    eqLoudness = "تعزيز علو الصوت",
    eqSavePreset = "حفظ الإعداد المسبق",
    eqReset = "إعادة ضبط",
    settingsTitle = "الإعدادات",
    settingsAppearance = "المظهر",
    settingsThemeMode = "وضع المظهر",
    settingsThemeLight = "فاتح",
    settingsThemeDark = "داكن",
    settingsThemeSystem = "تلقائي حسب النظام",
    settingsMaterialYou = "Material You (ألوان ديناميكية)",
    settingsDynamicColorArtwork = "استخراج الألوان من غلاف الأغنية",
    settingsAudio = "التحكم بالصوت",
    settingsCrossfade = "التداخل بين الأغاني (بالثواني)",
    settingsGapless = "التشغيل بدون فجوات",
    settingsFadeIn = "خفوت تدريجي عند التشغيل",
    settingsFadeOut = "خفوت تدريجي عند الإيقاف المؤقت",
    settingsLibraryScan = "إعدادات الفحص",
    settingsMinDuration = "تجاهل المقاطع الأقصر من (ثوانٍ)",
    settingsMinSize = "تجاهل الملفات الأصغر من (كيلوبايت)",
    settingsPerformance = "الأداء",
    settingsEnableBlur = "تفعيل تأثير الضباب والزجاج (Blur)",
    settingsBackup = "النسخ الاحتياطي والاستعادة",
    settingsBackupLocal = "نسخ احتياطي إلى ملف محلي",
    settingsRestoreLocal = "استعادة من ملف محلي",
    settingsLanguage = "اللغة / Language",
    settingsAbout = "حول داجو ميوزك",
    settingsVersion = "الإصدار 1.1.0",
    actionPlay = "تشغيل",
    actionPlayNext = "تشغيل التالي",
    actionAddToQueue = "إضافة لقائمة الانتظار",
    actionAddToPlaylist = "إضافة إلى قائمة تشغيل",
    actionFavorite = "إضافة للمفضلة",
    actionRemoveFavorite = "إزالة من المفضلة",
    actionShare = "مشاركة الملف",
    actionDelete = "حذف نهائي",
    actionRename = "إعادة تسمية الملف",
    actionProperties = "الخصائص",
    actionOpenFolder = "فتح المجلد",
    actionCancel = "إلغاء",
    actionSave = "حفظ",
    actionOk = "موافق",
    searchPlaceholder = "ابحث عن أغاني، فنانين، ألبومات، مجلدات…",
    searchRecent = "عمليات البحث الأخيرة",
    searchNoResults = "لا توجد نتائج",
    playbackSpeed = "سرعة التشغيل",
    playbackPitch = "حدة الصوت (Pitch)",
    playbackBalance = "توازن الصوت",
    playbackLyrics = "الكلمات",
    playbackSleepTimer = "مؤقت النوم",
    sleepTimerOff = "مؤقت النوم مغلق",
    sleepTimerMinutes = "%1\$d دقيقة",
    sleepTimerCustom = "وقت مخصص (بالدقائق)",
    sleepTimerSet = "ضبط مؤقت النوم",
    metaTitle = "العنوان",
    metaArtist = "الفنان",
    metaAlbum = "الألبوم",
    metaPath = "المسار",
    metaSize = "الحجم",
    metaDuration = "المدة",
    metaBitrate = "معدل البت",
    metaSampleRate = "معدل العينة",
    metaCodec = "الترميز",
    metaComposer = "الملحن",
    metaGenre = "النوع الموسيقي",
    metaYear = "السنة",
    msgScanning = "جاري فحص المكتبة…",
    msgScanComplete = "اكتمل الفحص. تم العثور على %1\$d أغنية.",
    msgBackupSuccess = "تم حفظ النسخة الاحتياطية بنجاح!",
    msgRestoreSuccess = "تمت استعادة المكتبة بنجاح!",
    msgRestoreFailed = "فشلت الاستعادة: الملف غير صالح.",
    msgDeleteConfirm = "هل أنت متأكد من رغبتك في حذف هذا الملف نهائياً من جهازك؟ لا يمكن التراجع عن هذا الإجراء.",
    msgUnsupportedFile = "تعذر تشغيل الملف. تنسيق غير مدعوم."
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }
